FROM php:8.1-apache

RUN apt-get update

RUN apt-get install -y \
    pkg-config  \
    libpq-dev \
    libzip-dev \
    libpng-dev \
    zip \
    supervisor

RUN docker-php-ext-install \
    mysqli \
    pdo \
    pdo_mysql \
    zip \
    && docker-php-ext-enable opcache



COPY --chown=root:root supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]