FROM php:8.1-apache

RUN apt-get update

RUN apt-get install -y \
    pkg-config  \
    libpq-dev \
    libzip-dev \
    libpng-dev \
    zip \
    cron

RUN docker-php-ext-install \
    mysqli \
    pdo \
    pdo_mysql \
    zip \
    && docker-php-ext-enable opcache

COPY crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab
RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log