name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www/html
        links:
            - cron
            - mysql
            - redis
    cron:
        build:
            context: ./docker
            dockerfile: Dockerfile.cron
        volumes:
            - .:/var/www/html
    
    mysql:
        image: mysql:8
        ports:
            - "${DB_HOST_PORT}:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        ports:
            - "${REDIS_HOST_PORT}:6379"
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
